helmDefaults:
  kubeContext: docker-desktop
  createNamespace: true

releases:
  - name: tempo
    namespace: grafana
    chart: ./charts/tempo
    values:
      - ./values/tempo.yaml


  - name: opentelemetry-collector
    namespace: monitoring
    chart: ./charts/opentelemetry-collector
    values:
      - ./values/opentelemetry-collector.yaml

  - name: kube-prometheus-stack
    namespace: prometheus
    chart: ./charts/kube-prometheus-stack
    values:
      - ./values/kube-prometheus-stack.yaml

  - name: grafana
    namespace: grafana
    chart: ./charts/grafana
    values:
      - ./values/grafana.yaml
  
  - name: alloy
    namespace: alloy
    chart: ./charts/alloy
    values:
      - ./values/alloy.yaml