name: Build and Push Docker Image
run-name: CI - ${{ github.sha }}

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 -t kyeongjundev/springboot:${{ github.sha }} example/springboot --push

      # Docker 이미지 푸시
      - name: Push Docker Image
        run: |
          docker push kyeongjundev/springboot:${{ github.sha }}